// NOTE: kept as inline-style object to avoid introducing CSS changes.
// Splitting it out of the page dramatically reduces the page file size.

export const s = {
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    flexWrap: "wrap",
    gap: 12,
  },
  h1: { fontSize: 24, fontWeight: 800, margin: 0 },
  searchInput: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    fontSize: 14,
    outline: "none",
    minWidth: 220,
  },
  select: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    fontSize: 14,
    cursor: "pointer",
    background: "#fff",
  },
  tableWrap: {
    background: "#fff",
    borderRadius: 12,
    overflow: "auto",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    border: "1px solid #e2e8f0",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    padding: "12px 14px",
    fontSize: 12,
    fontWeight: 700,
    color: "#475569",
    textAlign: "right",
    borderBottom: "1px solid #e2e8f0",
    whiteSpace: "nowrap",
  },
  tr: { borderBottom: "1px solid #f1f5f9", transition: "background 0.1s" },
  td: { padding: "12px 14px", fontSize: 13, verticalAlign: "middle" },
  sub: { fontSize: 11, color: "#94a3b8", marginTop: 1 },
  auditMeta: {
    fontSize: 10,
    color: "#b0bec5",
    marginTop: 3,
    lineHeight: 1.4,
    display: "flex",
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
  },
  idBadge: {
    background: "#f1f5f9",
    color: "#475569",
    borderRadius: 6,
    padding: "2px 7px",
    fontSize: 12,
    fontWeight: 700,
  },
  btnIcon: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 16,
    padding: "2px 5px",
    borderRadius: 5,
  },
  btnPrimary: {
    background: "#1d4ed8",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 18px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
  },
  btnSecondary: {
    background: "#f1f5f9",
    color: "#475569",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    padding: "8px 18px",
    fontWeight: 600,
    cursor: "pointer",
  },
  customerLinkBtn: {
    background: "transparent",
    border: "none",
    padding: 0,
    margin: 0,
    color: "#1d4ed8",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
    textDecoration: "underline",
    textUnderlineOffset: 2,
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  label: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "#475569",
    marginBottom: 5,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    fontSize: 12,
    color: "#475569",
  },
  timeHint: { fontSize: 10, color: "#94a3b8", fontWeight: 400, marginRight: 4 },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 12,
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
    flexWrap: "wrap",
  },
  errorBox: {
    background: "#fef2f2",
    color: "#dc2626",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    marginTop: 8,
  },
  pricePreview: {
    background: "#eff6ff",
    color: "#1d4ed8",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 14,
    marginBottom: 8,
  },
  pagination: { display: "flex", gap: 6, justifyContent: "center", marginTop: 16 },
  pageBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 13,
  },

  conflictIntro: {
    background: "linear-gradient(90deg, #fff7ed 0%, #fffbeb 100%)",
    border: "1px solid #fed7aa",
    borderRadius: 12,
    padding: "12px 14px",
    fontSize: 13,
    color: "#9a3412",
    marginBottom: 12,
  },
  conflictFilters: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 10,
    marginBottom: 10,
  },
  conflictFilterField: { display: "flex", flexDirection: "column", gap: 4 },
  conflictFilterLabel: { fontSize: 12, color: "#475569", fontWeight: 600 },
  conflictClearBtn: {
    marginRight: 6,
    fontSize: 10,
    padding: "1px 6px",
    borderRadius: 4,
    border: "1px solid #cbd5e1",
    background: "#f1f5f9",
    cursor: "pointer",
    color: "#64748b",
  },
  conflictFilterScroll: {
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    background: "#fff",
    maxHeight: 130,
    overflowY: "auto",
    padding: "4px 0",
  },
  conflictFilterItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 10px",
    cursor: "pointer",
    fontSize: 12,
    color: "#374151",
  },
  conflictFilterInput: {
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    padding: "8px 10px",
    fontSize: 13,
    background: "#fff",
  },
  newBookingCardWrap: {
    marginBottom: 12,
    border: "1px solid #bfdbfe",
    borderRadius: 12,
    background: "linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%)",
    padding: 10,
  },
  conflictLegend: {
    marginTop: 8,
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    fontSize: 11,
    color: "#475569",
  },
  conflictTableWrap: {
    maxHeight: 450,
    overflow: "auto",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
  },
  conflictTable: {
    borderCollapse: "collapse",
    width: "100%",
    minWidth: 780,
    tableLayout: "fixed",
  },
  conflictTh: {
    background: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    padding: "8px 6px",
    fontSize: 11,
    color: "#334155",
    whiteSpace: "nowrap",
    position: "sticky",
    top: 0,
    zIndex: 2,
  },
  conflictCarMeta: { marginTop: 2, fontSize: 10, color: "#64748b", fontWeight: 600 },
  conflictStickyCorner: { right: 0, zIndex: 3 },
  conflictTd: {
    borderBottom: "1px solid #f1f5f9",
    padding: "6px 4px",
    fontSize: 11,
    textAlign: "center",
    verticalAlign: "middle",
  },
  conflictStickyDate: {
    position: "sticky",
    right: 0,
    background: "#f8fafc",
    color: "#334155",
    fontWeight: 700,
    zIndex: 1,
  },
  conflictCard: {
    borderRadius: 8,
    padding: "8px 10px",
    border: "1px solid",
    fontSize: 12,
    fontWeight: 600,
    marginBottom: 6,
    userSelect: "none",
  },
  newBookingCard: {
    background: "#eff6ff",
    borderColor: "#60a5fa",
    borderStyle: "dashed",
    borderWidth: 2,
    color: "#1d4ed8",
    cursor: "grab",
    marginBottom: 0,
    padding: "12px 14px",
    boxShadow: "0 8px 22px rgba(37,99,235,0.18)",
  },
  newBookingBadge: {
    display: "inline-block",
    background: "#2563eb",
    color: "#fff",
    borderRadius: 999,
    padding: "2px 10px",
    fontSize: 10,
    fontWeight: 800,
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  newBookingTitle: { fontSize: 14, fontWeight: 800, marginBottom: 3 },
  newBookingMeta: { fontSize: 12, fontWeight: 600, color: "#1e3a8a" },
  conflictCellCard: {
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    padding: "4px 6px",
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    userSelect: "none",
    background: "#fff",
  },
  fullDragHint: { marginTop: 3, fontSize: 10, fontWeight: 700, color: "#1d4ed8" },
  blockerHint: { marginTop: 2, fontSize: 10, fontWeight: 700, color: "#991b1b" },
  conflictMetaText: { marginTop: 3, fontSize: 10, color: "#475569", fontWeight: 500 },
  conflictFooter: { marginTop: 10, display: "flex", alignItems: "center", gap: 10 },
  conflictWorking: { color: "#475569", fontSize: 12, fontWeight: 600 },

  // Smart suggestions panel (currently kept, used in the old file; harmless if unused)
  suggestLoading: {
    marginTop: 10,
    padding: "10px 14px",
    background: "#fefce8",
    border: "1px solid #fde68a",
    borderRadius: 8,
    color: "#92400e",
    fontSize: 13,
  },
  suggestPanel: { marginTop: 10, border: "1px solid #e0e7ff", borderRadius: 10, overflow: "hidden" },
  suggestTitle: {
    background: "#eef2ff",
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: 13,
    color: "#3730a3",
    borderBottom: "1px solid #e0e7ff",
  },
  suggestCard: { padding: "12px 14px", borderBottom: "1px solid #f1f5f9", background: "#fff" },
  typeBadge: {
    display: "inline-block",
    borderRadius: 999,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 700,
    border: "1px solid",
    marginLeft: 6,
  },
  carName: { fontWeight: 700, fontSize: 14, color: "#0f172a" },
  carMeta: { fontSize: 11, color: "#64748b" },
  suggestSummary: { marginTop: 5, fontSize: 12, color: "#475569" },
  suggestMeta: { marginTop: 4, fontSize: 11, color: "#7c3aed", fontWeight: 600 },
  btnAlt: {
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "6px 14px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 12,
  },
  customerDropdown: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "calc(100% + 4px)",
    zIndex: 20,
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    boxShadow: "0 8px 20px rgba(15,23,42,0.08)",
    maxHeight: 200,
    overflowY: "auto",
  },
  customerItem: {
    width: "100%",
    textAlign: "right",
    border: "none",
    background: "transparent",
    padding: "8px 10px",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  customerItemMuted: { padding: "8px 10px", fontSize: 12, color: "#64748b" },
  customerMeta: { fontSize: 11, color: "#64748b" },
  cooldownBox: {
    padding: "6px 10px",
    background: "#fff7ed",
    border: "1px solid #fdba74",
    color: "#9a3412",
    borderRadius: 6,
    fontSize: 12,
    marginBottom: 6,
  },
  riskBadge: (level) => ({
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 6px",
    borderRadius: 999,
    background: level === "low" ? "#dcfce7" : level === "medium" ? "#fef9c3" : "#fee2e2",
    color: level === "low" ? "#166534" : level === "medium" ? "#854d0e" : "#991b1b",
    flexShrink: 0,
  }),

  // Date filter bar
  dateFilterBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 14,
    padding: "8px 12px",
    background: "#f8fafc",
    borderRadius: 10,
    border: "1px solid #e2e8f0",
  },
  dateFilterBtn: {
    padding: "5px 14px",
    borderRadius: 999,
    border: "1px solid #e2e8f0",
    background: "#fff",
    color: "#475569",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 500,
  },
  dateFilterBtnActive: {
    padding: "5px 14px",
    borderRadius: 999,
    border: "1px solid #1d4ed8",
    background: "#1d4ed8",
    color: "#fff",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 700,
  },
  datePickerInline: {
    padding: "5px 10px",
    borderRadius: 8,
    border: "1px solid #cbd5e1",
    fontSize: 13,
    outline: "none",
    background: "#fff",
  },
  dateFilterHint: { fontSize: 12, color: "#1d4ed8", fontWeight: 600, marginRight: 4 },
  durationBtn: {
    padding: "3px 10px",
    borderRadius: 999,
    border: "1px solid #cbd5e1",
    background: "#f1f5f9",
    color: "#334155",
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  mobileCardsWrap: { display: "grid", gap: 10 },
  mobileCard: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 10,
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  mobileCardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  mobileTitle: { fontSize: 15, fontWeight: 700, color: "#0f172a" },
  mobileCustomerLinkBtn: {
    background: "transparent",
    border: "none",
    padding: 0,
    margin: 0,
    fontSize: 15,
    fontWeight: 800,
    color: "#1d4ed8",
    textDecoration: "underline",
    textUnderlineOffset: 2,
    cursor: "pointer",
    textAlign: "right",
    alignSelf: "flex-start",
  },
  mobileDates: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 6,
    marginTop: 8,
    fontSize: 12,
    color: "#334155",
  },
  mobileFooter: { marginTop: 8, display: "flex", justifyContent: "space-between", alignItems: "center" },
  mobileEmpty: {
    textAlign: "center",
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 24,
    color: "#94a3b8",
  },
};

